### ISSUE TITLE
Get Waifu exception message not populating on fail

### ISSUE THREAD

**Issue by austin1965** [baneetparmar/nuub_bot#37]
Not receiving any output on the waifu command (nuub_bot>cogs>bored>get_waifu.py) when it fails. Function has an exception block that should output a message on failure. No message is received on failure. 

Tested the following:
nb.waifu
nb.waifu test
nb.waifu sakura

No output received.

**Comment by baneetparmar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix #37](https://trello.com/c/Jn5zomBV/77-fix-37)
