### ISSUE TITLE
Paper trader commands aren't creating any output.

### ISSUE THREAD

**Issue by austin1965** [baneetparmar/nuub_bot#39]
Did not receive any output for the following commands:

nb.newacc
nb.price
nb.buy
nb.sell
nb.balance
nb.coins
nb.portfolio

**Comment by ilikechicken67** [comment]
Unsure why they were down, restarted bot and they work now so closing issue

**Comment by baneetparmar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix #39](https://trello.com/c/whQH0lWQ/76-fix-39)
